version: '3.7'
services:
  bot:
    restart: always
    build:
      context: ..
      dockerfile: docker/bot/Dockerfile
    # command: /usr/local/bin/supercronic supercronic.conf
    command: python3 run_live.py
    volumes:
    - ../generated:/opt/bot/generated
